version: '3.7'

networks:
  proxy-net:
    external:
      name: proxy-net

volumes:
  data:

services:
  mtproxy:
    image: mtproxy
    ports:
      - target: 4430
        protocol: tcp
        published: 4430
        mode: host
    volumes:
      - data:/data
    environment:
      - USER_SECRET=f5f4bbf7b2ff7f635c357a72f54b9fa1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ulimits:
      nproc: 65535
      nofile:
        soft: 999999
        hard: 999999
    networks:
      proxy-net:
        ipv4_address: 172.19.0.2
